Form Component
manishprivet/bookr pull request #15
Opened 2021-05-05 16:34 UTC by sejaljain123

#7 Form Component
Sign in and Register  Form
sub-issue of #2

2021-05-05 18:25 UTC, manishprivet requested changes

2021-05-05 18:25 UTC, manishprivet commented on src/components/Footer/Footer.scss
>  @media screen and (min-width: 0px) and (max-width: 400px) {
We don't need the min-width property here as keeping it as 0 is useless.

2021-05-05 18:25 UTC, manishprivet commented on src/components/Footer/Footer.scss
> +
Unused whitespaces should be avoided.

2021-05-05 18:35 UTC, sejaljain123 commented on src/components/Footer/Footer.scss
>  @media screen and (min-width: 0px) and (max-width: 400px) {
Got it!

2021-05-05 18:36 UTC, sejaljain123 commented on src/components/Footer/Footer.scss
> +
okay 😅

2021-05-06 11:41 UTC, manishprivet approved these changes

2021-05-06 11:45 UTC, merged